# Generated by Django 4.2.11 on 2024-04-10 08:33

import ckeditor.fields
import cloudinary.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import outlinecompilation.models


class Migration(migrations.Migration):

    dependencies = [
        ('outlinecompilation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuanDauRaMonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('mo_ta', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('so_thu_tu_chuong', models.IntegerField(default=0)),
                ('ten_chuong', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeCuongMonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('phuong_phap_giang_day_hoc_tap', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ten_khoa', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nganh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ten_nganh', models.CharField(max_length=50)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outlinecompilation.khoa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(default=1, verbose_name=outlinecompilation.models.User.VaiTro),
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nganh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlinecompilation.nganh')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('outlinecompilation.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MucTieuMonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('mo_ta', ckeditor.fields.RichTextField()),
                ('de_cuong_mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlinecompilation.decuongmonhoc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ten_mon_hoc', models.CharField(max_length=100)),
                ('so_tin_chi_thuc_hanh', models.FloatField(default=0)),
                ('so_tin_chi_ly_thuyet', models.FloatField(default=0)),
                ('so_tin_chi_tu_hoc', models.FloatField(default=0)),
                ('mo_ta_mon_hoc', ckeditor.fields.RichTextField()),
                ('mon_hoc_truoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mht', to='outlinecompilation.monhoc')),
                ('mon_song_hanh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msh', to='outlinecompilation.monhoc')),
                ('mon_tien_quyet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtq', to='outlinecompilation.monhoc')),
                ('nganh', models.ManyToManyField(to='outlinecompilation.nganh')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoaiCDRCTDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('tenLoai', models.CharField(max_length=255)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlinecompilation.khoa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeHoachGiangDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('tuan', models.IntegerField(default=0)),
                ('noi_dung_chuong', models.CharField(max_length=1000)),
                ('chuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlinecompilation.chuong')),
                ('de_cuong_mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlinecompilation.decuongmonhoc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HocLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('tenHocLieu', models.CharField(max_length=500)),
                ('de_cuong_mon_hoc', models.ManyToManyField(to='outlinecompilation.decuongmonhoc')),
                ('ke_hoach_giang_day', models.ManyToManyField(to='outlinecompilation.kehoachgiangday')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoatDongDayVaHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('so_tiet', models.FloatField(default=0)),
                ('congViec', ckeditor.fields.RichTextField()),
                ('loaiHoatDong', models.CharField(max_length=30)),
                ('ke_hoach_giang_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlinecompilation.kehoachgiangday')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=30)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlinecompilation.khoa')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('outlinecompilation.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Diem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ty_trong', models.FloatField(default=0)),
                ('hinh_thuc_danh_gia', models.CharField(max_length=50)),
                ('chuan_dau_ra_mon_hoc', models.ManyToManyField(to='outlinecompilation.chuandauramonhoc')),
                ('de_cuong_mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlinecompilation.decuongmonhoc')),
            ],
        ),
        migrations.AddField(
            model_name='decuongmonhoc',
            name='giang_vien_bien_soan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlinecompilation.giangvien'),
        ),
        migrations.AddField(
            model_name='decuongmonhoc',
            name='mon_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outlinecompilation.monhoc'),
        ),
        migrations.AddField(
            model_name='chuong',
            name='mon_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlinecompilation.monhoc'),
        ),
        migrations.AddField(
            model_name='chuandauramonhoc',
            name='muc_tieu_mon_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlinecompilation.muctieumonhoc'),
        ),
        migrations.CreateModel(
            name='ChuanDauRaCTDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('mo_ta', ckeditor.fields.RichTextField()),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlinecompilation.khoa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
