# Generated by Django 4.2.11 on 2024-04-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlinecompilation', '0002_chuandauramonhoc_chuong_decuongmonhoc_khoa_nganh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monhoc',
            name='mon_hoc_truoc',
        ),
        migrations.RemoveField(
            model_name='monhoc',
            name='mon_song_hanh',
        ),
        migrations.RemoveField(
            model_name='monhoc',
            name='mon_tien_quyet',
        ),
        migrations.AddField(
            model_name='monhoc',
            name='mon_hoc_truoc',
            field=models.ManyToManyField(blank=True, null=True, related_name='mht', to='outlinecompilation.monhoc'),
        ),
        migrations.AddField(
            model_name='monhoc',
            name='mon_song_hanh',
            field=models.ManyToManyField(blank=True, null=True, related_name='msh', to='outlinecompilation.monhoc'),
        ),
        migrations.AddField(
            model_name='monhoc',
            name='mon_tien_quyet',
            field=models.ManyToManyField(blank=True, null=True, related_name='mtq', to='outlinecompilation.monhoc'),
        ),
    ]
