# Generated by Django 4.2.11 on 2024-04-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlinecompilation', '0003_remove_monhoc_mon_hoc_truoc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giangvien',
            options={'verbose_name': 'Giang vien'},
        ),
        migrations.AlterModelOptions(
            name='sinhvien',
            options={'verbose_name': 'Sinh vien'},
        ),
        migrations.RemoveField(
            model_name='chuandauractdt',
            name='khoa',
        ),
        migrations.RemoveField(
            model_name='loaicdrctdt',
            name='khoa',
        ),
        migrations.AddField(
            model_name='chuandauractdt',
            name='nganh',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='outlinecompilation.nganh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loaicdrctdt',
            name='nganh',
            field=models.ManyToManyField(to='outlinecompilation.nganh'),
        ),
    ]
