# Generated by Django 4.2.11 on 2024-04-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlinecompilation', '0004_alter_giangvien_options_alter_sinhvien_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoclieu',
            old_name='tenHocLieu',
            new_name='ten_hoc_lieu',
        ),
        migrations.RenameField(
            model_name='loaicdrctdt',
            old_name='tenLoai',
            new_name='ten_loai',
        ),
    ]
