# Generated by Django 4.2.11 on 2024-04-10 11:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('outlinecompilation', '0005_rename_tenhoclieu_hoclieu_ten_hoc_lieu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuandauractdt',
            name='loaicdrctdt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='outlinecompilation.loaicdrctdt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diem',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
