# Generated by Django 4.2.11 on 2024-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlinecompilation', '0006_chuandauractdt_loaicdrctdt_diem_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chuandauramonhoc',
            name='muc_tieu_mon_hoc',
        ),
        migrations.AddField(
            model_name='chuandauramonhoc',
            name='muc_tieu_mon_hoc',
            field=models.ManyToManyField(to='outlinecompilation.muctieumonhoc'),
        ),
    ]
