# Generated by Django 4.2.11 on 2024-04-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlinecompilation', '0007_remove_chuandauramonhoc_muc_tieu_mon_hoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muctieumonhoc',
            name='chuan_dau_ra_ctdt',
            field=models.ManyToManyField(to='outlinecompilation.chuandauractdt'),
        ),
        migrations.RemoveField(
            model_name='chuandauramonhoc',
            name='muc_tieu_mon_hoc',
        ),
        migrations.AddField(
            model_name='chuandauramonhoc',
            name='muc_tieu_mon_hoc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='outlinecompilation.muctieumonhoc'),
            preserve_default=False,
        ),
    ]
