# Generated by Django 4.2.11 on 2024-04-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlinecompilation', '0008_muctieumonhoc_chuan_dau_ra_ctdt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuandauractdt',
            name='stt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loaicdrctdt',
            name='stt',
            field=models.IntegerField(default=0),
        ),
    ]
