# Generated by Django 4.2.11 on 2024-04-22 14:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0002_khoa_nganh_sinhvien_giangvien'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuanDauRaCTDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('stt', models.IntegerField(default=0)),
                ('mo_ta', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChuanDauRaMonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('stt', models.IntegerField(default=0)),
                ('mo_ta', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('so_thu_tu_chuong', models.IntegerField(default=0)),
                ('ten_chuong', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeCuongMonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('phuong_phap_giang_day_hoc_tap', ckeditor.fields.RichTextField()),
                ('nam_bien_soan', models.IntegerField(default='2024')),
                ('giang_vien_bien_soan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outline.giangvien')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MucTieuMonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('stt', models.IntegerField(default=0)),
                ('mo_ta', ckeditor.fields.RichTextField()),
                ('chuan_dau_ra_ctdt', models.ManyToManyField(to='outline.chuandauractdt')),
                ('de_cuong_mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.decuongmonhoc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ten_mon_hoc', models.CharField(max_length=100)),
                ('so_tin_chi_thuc_hanh', models.FloatField(default=0)),
                ('so_tin_chi_ly_thuyet', models.FloatField(default=0)),
                ('so_tin_chi_tu_hoc', models.FloatField(default=0)),
                ('mo_ta_mon_hoc', ckeditor.fields.RichTextField()),
                ('mon_hoc_truoc', models.ManyToManyField(blank=True, null=True, related_name='mht', to='outline.monhoc')),
                ('mon_song_hanh', models.ManyToManyField(blank=True, null=True, related_name='msh', to='outline.monhoc')),
                ('mon_tien_quyet', models.ManyToManyField(blank=True, null=True, related_name='mtq', to='outline.monhoc')),
                ('nganh', models.ManyToManyField(to='outline.nganh')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoaiCDRCTDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('stt', models.IntegerField(default=0)),
                ('ten_loai', models.CharField(max_length=255)),
                ('nganh', models.ManyToManyField(to='outline.nganh')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeHoachGiangDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('tuan', models.IntegerField(default=0)),
                ('noi_dung_chuong', models.CharField(max_length=1000)),
                ('chuong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.chuong')),
                ('de_cuong_mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.decuongmonhoc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HocLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ten_hoc_lieu', models.CharField(max_length=500)),
                ('de_cuong_mon_hoc', models.ManyToManyField(to='outline.decuongmonhoc')),
                ('ke_hoach_giang_day', models.ManyToManyField(to='outline.kehoachgiangday')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoatDongDayVaHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('so_tiet', models.FloatField(default=0)),
                ('congViec', ckeditor.fields.RichTextField()),
                ('loaiHoatDong', models.CharField(max_length=30)),
                ('ke_hoach_giang_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.kehoachgiangday')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ty_trong', models.FloatField(default=0)),
                ('hinh_thuc_danh_gia', models.CharField(max_length=50)),
                ('phan_loai', models.CharField(choices=[('QT', 'Quatrinh'), ('GK', 'Giuaky'), ('CK', 'Cuoiky')], max_length=2)),
                ('chuan_dau_ra_mon_hoc', models.ManyToManyField(to='outline.chuandauramonhoc')),
                ('de_cuong_mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.decuongmonhoc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='decuongmonhoc',
            name='mon_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outline.monhoc'),
        ),
        migrations.AddField(
            model_name='chuong',
            name='mon_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.monhoc'),
        ),
        migrations.AddField(
            model_name='chuandauramonhoc',
            name='muc_tieu_mon_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.muctieumonhoc'),
        ),
        migrations.AddField(
            model_name='chuandauractdt',
            name='loaicdrctdt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outline.loaicdrctdt'),
        ),
        migrations.AddField(
            model_name='chuandauractdt',
            name='nganh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outline.nganh'),
        ),
    ]
