# Generated by Django 4.2.11 on 2024-04-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0003_chuandauractdt_chuandauramonhoc_chuong_decuongmonhoc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decuongmonhoc',
            name='nam_bien_soan',
        ),
        migrations.AddField(
            model_name='monhoc',
            name='ten_mon_hoc_ta',
            field=models.CharField(default='ABC', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monhoc',
            name='thuoc_khoi_kien_thuc',
            field=models.CharField(default='Cơ bản', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='mon_hoc_truoc',
            field=models.ManyToManyField(blank=True, related_name='mht', to='outline.monhoc'),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='mon_song_hanh',
            field=models.ManyToManyField(blank=True, related_name='msh', to='outline.monhoc'),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='mon_tien_quyet',
            field=models.ManyToManyField(blank=True, related_name='mtq', to='outline.monhoc'),
        ),
    ]
