# Generated by Django 4.2.11 on 2024-05-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0006_rename_congviec_hoatdongdayvahoc_cong_viec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diem',
            name='chuan_dau_ra_mon_hoc',
        ),
        migrations.RemoveField(
            model_name='hoclieu',
            name='de_cuong_mon_hoc',
        ),
        migrations.RemoveField(
            model_name='hoclieu',
            name='ke_hoach_giang_day',
        ),
        migrations.RemoveField(
            model_name='loaicdrctdt',
            name='nganh',
        ),
        migrations.AddField(
            model_name='chuandauramonhoc',
            name='diem',
            field=models.ManyToManyField(to='outline.diem'),
        ),
        migrations.AddField(
            model_name='decuongmonhoc',
            name='hoc_lieu',
            field=models.ManyToManyField(to='outline.hoclieu'),
        ),
        migrations.AddField(
            model_name='kehoachgiangday',
            name='hoc_lieu',
            field=models.ManyToManyField(to='outline.hoclieu'),
        ),
        migrations.AddField(
            model_name='nganh',
            name='loaiCDRCTDT',
            field=models.ManyToManyField(to='outline.loaicdrctdt'),
        ),
    ]
