# Generated by Django 4.2.11 on 2024-05-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0007_remove_diem_chuan_dau_ra_mon_hoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monhoc',
            name='so_tin_chi',
            field=models.FloatField(default=0),
        ),
    ]
