# Generated by Django 4.2.11 on 2024-06-01 13:47

from django.db import migrations, models
import outline.models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0008_monhoc_so_tin_chi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(verbose_name=outline.models.User.VaiTro),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
