# Generated by Django 4.2.11 on 2024-06-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0009_alter_user_password_alter_user_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giangvien',
            name='degree',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='giangvien',
            name='khoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='outline.khoa'),
        ),
        migrations.AlterField(
            model_name='giangvien',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='nganh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='outline.nganh'),
        ),
    ]
