# Generated by Django 4.2.11 on 2024-06-03 03:15

from django.db import migrations, models
import outline.models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0010_alter_giangvien_degree_alter_giangvien_khoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='outline/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(null=True, verbose_name=outline.models.User.VaiTro),
        ),
    ]
