# Generated by Django 4.2.11 on 2024-06-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0011_alter_user_avatar_alter_user_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monhoc',
            name='thuoc_khoi_kien_thuc',
        ),
        migrations.AddField(
            model_name='hoatdongdayvahoc',
            name='chuan_dau_ra_mon_hoc',
            field=models.ManyToManyField(to='outline.chuandauramonhoc'),
        ),
        migrations.AddField(
            model_name='hoclieu',
            name='de_cuong_mon_hoc',
            field=models.ManyToManyField(to='outline.decuongmonhoc'),
        ),
        migrations.AddField(
            model_name='hoclieu',
            name='stt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monhoc',
            name='ThuocKhoiKienThuc',
            field=models.CharField(choices=[('Giáo dục đại cương', 'Giaoducdaicuong'), ('Kiến thức cơ sở', 'Kienthuccoso'), ('Kiến thức ngành', 'Kienthucnganh'), ('Kiến thức chuyên ngành', 'Kienthucchuyennganh'), ('Kiến thức bổ trợ', 'Kienthucbotro'), ('Đồ án/Khóa luận tốt nghiệp', 'Doan Khoaluan')], default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hoatdongdayvahoc',
            name='loai_hoat_dong',
            field=models.CharField(choices=[('Học tại nhà', 'Hoctainha'), ('Học trên lớp', 'Hoctrenlop'), ('Thực hành phòng máy', 'Thuchanhphongmay'), ('Thực hành trên LMS', 'Thuchanhtrenlms'), ('Học trực tuyến', 'Hoctructuyen')], max_length=30),
        ),
    ]
