# Generated by Django 4.2.11 on 2024-06-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0012_remove_monhoc_thuoc_khoi_kien_thuc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MucDoDapUng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('muc_do_dap_ung', models.IntegerField(choices=[(1, 'Khongdapung'), (2, 'Itdapung'), (3, 'Dapungtrungbinh'), (4, 'Dapungnhieu'), (5, 'Dapungratnhieu')])),
                ('chuan_dau_ra_ctdt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.chuandauractdt')),
                ('chuan_dau_ra_mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.chuandauramonhoc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
