# Generated by Django 4.2.11 on 2024-06-11 15:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0016_decuongmonhoc_quy_dinh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoatdongdayvahoc',
            name='cong_viec',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
