# Generated by Django 4.2.11 on 2024-06-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0017_alter_hoatdongdayvahoc_cong_viec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoclieu',
            name='stt',
        ),
        migrations.AlterField(
            model_name='diem',
            name='phan_loai',
            field=models.CharField(choices=[('Quá trình', 'Quatrinh'), ('Giữa kỳ', 'Giuaky'), ('Cuối kỳ', 'Cuoiky')], max_length=9),
        ),
    ]
