# Generated by Django 4.2.11 on 2024-06-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outline", "0020_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(upload_to="outline/%Y/%m"),
        ),
    ]
