# Generated by Django 4.2.11 on 2024-06-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("outline", "0022_decuongmonhoc_hoc_lieu_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decuongmonhoc",
            name="hoc_lieu",
        ),
    ]
